### PR TITLE
Cache inlay hints to avoid flickering

### LINKED ISSUE #2468: Inlay hints flicker sometimes
### Swift version

Swift version 6.2.3 (swift-6.2.3-RELEASE)

### Platform

macOS Sequoia 15.4.1

### Editor

Visual Studio Code with the Swift Extension

### Description

Sometimes the inlay hints disappear for a short time before reappearing. This is probably due to the inlay hint calculation taking too long. When using soft wrapping this can cause the lines in the editor to visually shift. I have provided examples of what that looks like below. The first example shows the behavior as I normally observe it. For the second example I have added a 3-second delay at the end of the `inlayHint` method in the `SwiftLanguageService` extension in `InlayHints.swift` to exaggerate the effect.

Example:

https://github.com/user-attachments/assets/bfea6073-4b63-489a-b08c-27ff6ced98d4

Example with a 3-second delay before returning the inlay hints:

https://github.com/user-attachments/assets/4c531e70-8c5c-409b-bd4a-a896eaa6e2f2

I have also looked a bit into how other plugins deal with this, and it seems that they just recalculate the inlay hints fast enough. As far as I can tell this is also the intended solution as VSCode does not provide any API for caching the inlay hints or something similar. Caching the inlay hints in the language service may be an option, but it would probably be difficult to correctly invalidate this cache.

### Steps to Reproduce

1. Ensure soft wrapping is turned on (for VSCode: View -> Word Wrap)
2. Open an editor that contains swift source code with a long type hint, for example:
```swift
struct ReallyLongTypeNameStruct123456789 {}

let x = ReallyLongTypeNameStruct123456789()
```
3. Either make the VSCode window narrow enough or open a second editor next to the first one to force soft wrapping
4. Edit the file to force a recalculation of the inlay hints

### Logging

_No response_

### PR DESCRIPTION
**Pull request by Steffeeen**
Fixes #2468.

## Comparison
Before:

https://github.com/user-attachments/assets/abd4570b-2083-410e-809e-155adfe466f4

https://github.com/user-attachments/assets/13157ee3-d992-4a2e-9aa7-8efae977983a

After:

https://github.com/user-attachments/assets/b8e37145-927f-4447-a620-bc9ff1487956

https://github.com/user-attachments/assets/e9e510aa-7a2b-4abb-a4ac-85943bb1d774

## Description

Currently, we always recomputed the inlay hints by calling into SourceKit. If the document that we compute inlay hints for has recently changed, SourceKit may need a bit of time to perform parsing and semantic analysis. The inlay hints may thus need roughly 200-700ms to be computed. This causes flickering in VSCode as it removes the old inlay hints immediately and only displays them again when SourceKit-LSP returned them.

With this PR the inlay hints are cached and recomputed in the background. On each `textDocument/didChange` request the cached inlay hints are shifted according to the text edits to ensure their positions are still correct. This avoids the flickering as we always have inlay hints which we can return immediately. The returned hints may however temporarily show outdated type information until the background recompute is finished. This can be seen in the first example where the inlay hints need a short time to be updated.

## Open Questions / ToDo

There are still a few open questions which I need to think about, but I also wanted to get input on them as early as possible:

In the current version of this PR whenever the file changes, the inlay hints for the entire file are recomputed. I think this is not strictly necessary, but I'm also unsure how much of an impact it has compared to only computing inlay hints for a part of the document. The main thing that takes time for computing inlay hints is the parsing and semantic analysis of the file in SourceKit. I haven't looked into if it can do this incrementally or if it always does the semantic analysis for the entire file.

~~The inlay hints for `#if` directives are currently also cached, but I'm not sure that's necessary, they can maybe be recomputed each time.~~

~~It may currently also be possible to have a memory leak with the cache if the client disconnects/loses connection without sending a `didClose` request. This can maybe be handled by using a LRU cache or a timeout after which the cached inlay hints for a document are dropped if they were not accessed.~~

~~I also don't like the constant conversions between `Position`s and `AbsolutePosition`s in the code, but they probably can't be avoided.~~

## `DocumentSnapshot` changes 

I can also move the two commits for the `DocumentSnapshot` methods to a separate PR.

### CODE REVIEW

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 1]
```diff
@@ -12,10 +12,40 @@
...
+  let id: UUID
+  let expectedVersion: Int
+  let task: Task<Void, any Error>
+}
+
+struct InlayHintState {
+  /// Cached inlay hints for each document.
+  ///
+  /// Each entry stores hints for the full document and the document version they were computed for.
+  var cache: [DocumentURI: InlayHintCacheEntry] = [:]
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: I think I would prefer to make this an LRU cache similar to what we have for in the diagnostics manager and the syntax tree cache.

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 2]
```diff
@@ -30,28 +60,233 @@ package struct InlayHintResolveData: Codable, LSPAnyCodable {
...
   }
 }
 
+struct ShiftedInlayHint {
+  let inlayHint: InlayHint
+  let position: AbsolutePosition
+  let dataPosition: AbsolutePosition?
+  let textEdits: [ShiftedTextEdit]
+
+  func shiftBy(delta: SourceLength) -> ShiftedInlayHint {
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: This should be named `shiftedBy` to follow https://www.swift.org/documentation/api-design-guidelines/#name-according-to-side-effects.

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 3]
```diff
@@ -12,10 +12,40 @@
...
+  let hints: [InlayHint]
+}
+
+struct InFlightInlayHintRefreshTask {
+  let id: UUID
+  let expectedVersion: Int
+  let task: Task<Void, any Error>
+}
+
+struct InlayHintState {
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: Could we have an `InlayHintManager` similar to how we have a `SyntaxTreeManager` that takes care of all the position shifting etc. I think encapsulating all of that logic in one place will make it easier to reason about.

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 4]
```diff
@@ -30,28 +60,233 @@ package struct InlayHintResolveData: Codable, LSPAnyCodable {
...
+        guard snapshot.version == expectedVersion else {
+          return
+        }
+
+        let updatedEntry = InlayHintCacheEntry(version: snapshot.version, hints: updatedHints)
+        await self.storeInlayHintCache(updatedEntry, for: uri)
+
+        let _ = try await self.sourceKitLSPServer?.sendRequestToClient(InlayHintRefreshRequest())
+      } catch is CancellationError {
+        throw CancellationError()
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: I think this doesn’t do anything.

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 5]
```diff
@@ -30,28 +60,233 @@ package struct InlayHintResolveData: Codable, LSPAnyCodable {
...
+    guard let inFlightTask = inlayHintState.inFlightRefreshTasks[uri], inFlightTask.id == taskID else {
+      return
+    }
+    inlayHintState.inFlightRefreshTasks[uri] = nil
+
+    guard let latestVersion = try? documentManager.latestSnapshot(uri).version else {
+      return
+    }
+    if latestVersion > inFlightTask.expectedVersion {
+      scheduleInlayHintRefresh(for: uri, expectedVersion: latestVersion)
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: Could you add a comment why this is necessary?

File: Sources/SwiftLanguageService/SwiftLanguageService.swift [hunk 6]
```diff
@@ -759,9 +763,21 @@ extension SwiftLanguageService {
       edits: concurrentEdits
     )
 
+    shiftCachedInlayHints(
+      for: notification.textDocument.uri,
+      edits: edits,
+      preEditSnapshot: preEditSnapshot,
+      postEditSnapshot: postEditSnapshot
+    )
+    scheduleInlayHintRefresh(for: notification.textDocument.uri, expectedVersion: postEditSnapshot.version)
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/SwiftLanguageService.swift]: Actually, I wonder if we should be re-computing inlay hints on every edit to the document if we had inlay hints cached for a previous version of the document. Chances are very high that the client will need inlay hints for the next document version as well and this way there is a chance that we’ll already have them computed when the client asks for them (or at least reduces the amount of time until they are available). What do you think?

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 7]
```diff
@@ -30,28 +60,233 @@ package struct InlayHintResolveData: Codable, LSPAnyCodable {
...
+        try Task.checkCancellation()
+
+        guard snapshot.version == expectedVersion else {
+          return
+        }
+
+        let updatedEntry = InlayHintCacheEntry(version: snapshot.version, hints: updatedHints)
+        await self.storeInlayHintCache(updatedEntry, for: uri)
+
+        let _ = try await self.sourceKitLSPServer?.sendRequestToClient(InlayHintRefreshRequest())
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: My biggest concern with this approach is that this will cause the client to refresh inlay hints for *all* open documents, not just the one that we just re-computed the inlay hints for. I wonder if we could add an LSP extension to this request to only refresh a single document. That being said, I don’t think it’s a blocker and previous versions of inlay hints worked like this, so it’s probably fine – would just be a nice optimization.

@plemarquand Do you think it would be possible to add a middleware to the VS Code extension that captures `inlayHint/refresh` requests and only refreshes inlay hints for a single document as opposed to all?

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 8]
```diff
@@ -96,7 +338,47 @@ extension SwiftLanguageService {
...
+      currentHints = []
+
+      let lowerBoundIndex = previousHints.binarySearchFirst(where: { $0.position >= edit.range.lowerBound })
+      let upperBoundIndex = previousHints.binarySearchFirst(where: { $0.position >= edit.range.upperBound })
+
+      // Hints before the edit range are unaffected.
+      currentHints.append(contentsOf: previousHints[..<lowerBoundIndex])
+      // Hints that overlap with the edit range are dropped and will be recomputed in the background.
+      // Hints after the edit range need to be shifted by the edit delta.
+      currentHints.append(contentsOf: previousHints[upperBoundIndex...].map { $0.shiftBy(delta: delta) })
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]: Just a thought: Would it be possible to do the shifting in the `Position` line:column space instead of the `AbsolutePosition` offset-based space? I think it should work as well because we just need to add something to the line number if a line was inserted before and adjust the column if there was an edit on this line. Could be missing something though.

**Review by ahoppen — COMMENTED** [review]
Thanks. Would be great to get rid of that flickering 😄

File: Sources/SwiftLanguageService/InlayHints.swift (hunk 5 above)
Comment (Steffeeen) [reply Sources/SwiftLanguageService/InlayHints.swift]: I removed this check as I found it to be unnecessary.

File: Sources/SwiftLanguageService/SwiftLanguageService.swift (hunk 6 above)
Comment (Steffeeen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: I don't quite get what you are suggesting. The code already starts a Task for updating the inlay hints using SourceKit immediately when it receives a `textDocument/didChange`.

File: Sources/SwiftLanguageService/InlayHints.swift (hunk 8 above)
Comment (Steffeeen) [reply Sources/SwiftLanguageService/InlayHints.swift]: Yeah, that works, I initially rejected this idea because the `SourceEdit`s were using `Range<AbsolutePosition>`. However, I now pass in the `TextDocumentContentChangeEvent`s which use `Range<Position>`.

File: Sources/SwiftLanguageService/InlayHints.swift (hunk 7 above)
Comment (Steffeeen) [reply Sources/SwiftLanguageService/InlayHints.swift]: Yeah, I also don't like that this causes the client to refresh the inlay hints in all documents. However, according to the [spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_inlayHint_refresh):
> Note that the client still has the freedom to delay the re-calculation of the inlay hints if for example an editor is currently not visible."

So the client may not request the inlay hints for all open documents immediately. Additionally, the inlay hints for the open documents are cached so it's just a matter of returning the cached inlay hints. So this shouldn't trigger a SourceKit computation for all the other documents.

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 9]
```diff
@@ -0,0 +1,270 @@
...
+
+    var currentHints = cachedEntry.hints
+    for change in contentChanges {
+      guard let range = change.range else {
+        // Full document replacement. Invalidate all cached hints for the document, since we don't know how to shift them.
+        cache[uri] = nil
+        return
+      }
+
+      let lineDelta = change.text.count(where: { $0.isNewline }) - (range.upperBound.line - range.lowerBound.line)
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift]: Nitpick to make this read a little nicer.

```suggestion
      let lineDelta = change.text.count(where: \.isNewline) - (range.upperBound.line - range.lowerBound.line)
```

Similar below

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 10]
```diff
@@ -0,0 +1,270 @@
...
+      let columnDelta =
+        if let lastNewlineIndex = change.text.lastIndex(where: { $0.isNewline }) {
+          change.text.distance(from: change.text.index(after: lastNewlineIndex), to: change.text.endIndex)
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift]: I think we need to adjust by UTF-16 positions here instead of numbers of grapheme clusters.

```suggestion
          change.text.utf16.distance(from: change.text.index(after: lastNewlineIndex), to: change.text.endIndex)
```

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 11]
```diff
@@ -0,0 +1,270 @@
...
+        } else {
+          change.text.count
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift]:
```suggestion
          change.text.utf16.count
```

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 12]
```diff
@@ -0,0 +1,270 @@
...
+      if inFlightTask.expectedVersion >= snapshot.version {
+        // We already have a task running for a newer version of the document, so we don't need to schedule another one.
+        return
+      }
+      // Cancel the currently running task for the older version of the document, since we will schedule a new one for the newer version below.
+      inFlightTask.task.cancel()
+    }
+
+    let taskID = UUID()
+    let task = Task(priority: .medium) { [weak self, service] in
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift]: Since we capture `self` strongly, immediately when the task starts executing, I think we can avoid the `weak` dance here. It only has an affect if `InlayHintManager` would get destroyed after the task was created but before it starts executing, and that’s usually a very short time period.

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 13]
```diff
@@ -0,0 +1,270 @@
...
+      guard let self else {
+        return
+      }
+      defer { Task { await finishInlayHintRefresh(swiftLanguageService: service, for: uri, taskID: taskID) } }
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift]: Instead of spawning a `Task` here that may execute whenever, it would be nicer to use `run(_:cleanup:)` here. (At least until we get async defers).

With that, we might also be able to inline the implementation of `finsihInlayHintRefresh` here, which would help match the removal of tasks from `inFlightRefreshTasks` to where they are created.

File: Sources/SwiftLanguageService/InlayHints.swift [hunk 14]
```diff
@@ -12,71 +12,53 @@
...
-          textEdits: textEdits,
-          data: resolveData.encodeToLSPAny()
-        )
-      }
+    if let sourceKitLSPServer = self.sourceKitLSPServer,
+      let clientCapabilities = await sourceKitLSPServer.capabilityRegistry?.clientCapabilities,
+      !(clientCapabilities.workspace?.inlayHint?.refreshSupport ?? false)
+    {
+      // The client does not support workspace/inlayHint/refresh.
+      // We have to compute inlay hints on every request, because we cannot trigger a refresh when the document changes.
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHints.swift]:
```suggestion
      // We have to compute inlay hints on every request, because we cannot trigger a refresh when the inlay hints have been recomputed in the background.
```

File: Tests/SourceKitLSPTests/InlayHintTests.swift [hunk 15]
```diff
@@ -19,25 +19,92 @@ import XCTest
...
+    func getBackgroundComputedInlayHints() async throws -> [InlayHint] {
+      let refreshRequestReceived = testCase.expectation(description: "Receive first inlay hint refresh request")
+      testClient.handleSingleRequest { (_: InlayHintRefreshRequest) in
+        refreshRequestReceived.fulfill()
+        return VoidResponse()
+      }
+
+      let request = InlayHintRequest(textDocument: TextDocumentIdentifier(uri), range: range)
+      let _ = try await testClient.send(request)
+      await testCase.fulfillment(of: [refreshRequestReceived], timeout: 10)
```
Comment (ahoppen) [inline Tests/SourceKitLSPTests/InlayHintTests.swift]: CI can be surprisingly slow in some cases. I’d prefer if we just stick with the default timeout here.

File: Tests/SourceKitLSPTests/InlayHintTests.swift [hunk 16]
```diff
@@ -404,4 +509,202 @@ final class InlayHintTests: SourceKitLSPTestCase {
...
+    ) {
+      let hints = try await $0.getBackgroundComputedInlayHints()
+      assertHintsEqual(
+        hints,
+        [
+          makeInlayHint(position: $0.positions["3️⃣"], kind: .type, label: ": Int")
+        ]
+      )
+
+      $0.sendChange(
```
Comment (ahoppen) [inline Tests/SourceKitLSPTests/InlayHintTests.swift]: I generally prefer to only use the anonymous `$0` variables if the closure is a single line (or at least not significantly more), because it’s too easy to loose context of what `$0` is over multiple lines. Could you name the variable in the tests?

File: Tests/SourceKitLSPTests/InlayHintTests.swift [hunk 17]
```diff
@@ -404,4 +509,202 @@ final class InlayHintTests: SourceKitLSPTestCase {
...
+          let b: Int = 10
+          """
+      )
+
+      let shiftedHints = try await $0.getCachedInlayHints()
+      assertHintsEqual(
+        shiftedHints,
+        [
+          makeInlayHint(position: $0.positions["1️⃣"], kind: .type, label: ": Int"),
+          makeInlayHint(position: Position(line: 3, utf16index: 5), kind: .type, label: ": Int"),
```
Comment (ahoppen) [inline Tests/SourceKitLSPTests/InlayHintTests.swift]: Could we use a position marker here instead of hard-coding the position? Same for a few more test cases below.

File: Sources/SwiftLanguageService/InlayHints.swift (hunk 7 above)
Comment (ahoppen) [reply Sources/SwiftLanguageService/InlayHints.swift]: OK, I guess it’s fine in practice. Still would like to hear from Paul if we can improve this in the long term.

File: Sources/SwiftLanguageService/SwiftLanguageService.swift (hunk 6 above)
Comment (ahoppen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: I was wondering if we should schedule a background re-computation of inlay hints on every edit (just without sending the `inlayHint/refresh` request to the client once this one is finished. That way, if the editor sends an inlay hints request, say, 1s after the edit, we might have already computed the new inlay hints and we don’t need to take the `inlayHint/refresh` path at all. And even if re-computing the inlay hints takes 2s, then we will be able to show the inlay hints 1s earlier than if we only triggered the refresh when the client sends the inlay hint request.

What do you think? I think regardless, this could be an improvement for a follow-up PR.

File: Sources/SwiftLanguageService/InlayHints.swift (hunk 7 above)
Comment (plemarquand) [reply Sources/SwiftLanguageService/InlayHints.swift]: @ahoppen I think this would be tricky to implement; there isn't a middleware for the refresh notification in the VS Code language client API.  

The vscode-languageclient [requests a range](https://github.com/microsoft/vscode-languageserver-node/blob/main/client/src/common/inlayHint.ts#L69) when asking for inlay hints, so from the client's perspective its already asking for the bare minimum

Comment (ahoppen) [reply Sources/SwiftLanguageService/InlayHints.swift]: OK, in that case I think we just stick with the current design. I was just hoping that there would be a way to avoid the following situation:
- The user has two tabs open side-by-side in VS Code
- We send a `inlayHints/refresh` request because we re-computed the tokens for the left-hand editor
- VS Code would now also refresh the inlay hints for the right-hand editor

But it probably isn’t all that bad in practice.

File: Sources/SwiftLanguageService/SwiftLanguageService.swift (hunk 6 above)
Comment (Steffeeen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: The `InlayHintManager` currently already calls `scheduleInlayHintRefresh` in `processEdits` which accomplishes what you are suggesting. However, that of course does always trigger the `inlayHint/refresh` path currently. I'm now also realizing that we probably should not schedule a refresh if the client does not support `inlayHint/refresh` as the results of this inlay hint computation will never be used.

I think implementing this should simply be adding a bool to `scheduleInlayHintRefresh` indicating whether to send the refresh request at the end. I will try it out.

Comment (ahoppen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: Oh, I totally missed that. But doesn’t this mean that all the tests are also racy. If the inlay hint refresh triggered by the edit finishes before the tests send the `textDocument/inlayHints` requests, then we won’t trigger another `inlayHints/refresh` request and thus waiting for that will time out in the test.

File: Tests/SourceKitLSPTests/InlayHintTests.swift (hunk 17 above)
Comment (Steffeeen) [reply Tests/SourceKitLSPTests/InlayHintTests.swift]: I changed the code to use position markers where possible. In `testInlayHintShiftingWithMultipleChanges` the manual positions cannot really be avoided, due to the changes being incremental.

File: Sources/SwiftLanguageService/SwiftLanguageService.swift (hunk 6 above)
Comment (Steffeeen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: I guess that could have happened, although I haven't had that happen when executing the tests locally.

I added the capability check for processing the edits. I also added the bool to `scheduleInlayHintRefresh` so that we don't send the refresh request when a recomputation of the inlay hints was trigged by a change.

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 18]
```diff
@@ -0,0 +1,316 @@
...
+
+          if inFlightTask.sendRefreshRequest {
+            let _ = try await service.sourceKitLSPServer?.sendRequestToClient(InlayHintRefreshRequest())
+          }
+        } catch {
+          if error is CancellationError {
+            return
+          }
+          logger.error("Inlay hint refresh failed for \(uri.forLogging): \(error.forLogging)")
+        }
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift:235]: Could be slightly simplified

```suggestion
        } catch is CancellationError {
          return
        } catch {
          logger.error("Inlay hint refresh failed for \(uri.forLogging): \(error.forLogging)")
        }
```

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 19]
```diff
@@ -0,0 +1,316 @@
...
+  package init(uri: DocumentURI, position: Position, version: Int) {
+    self.uri = uri
+    self.position = position
+    self.version = version
+  }
+}
+
+private struct InlayHintCacheEntry {
+  let version: Int
+  let needsSemanticRefresh: Bool
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift:36]: Could you add a comment what exactly this means?

File: Sources/SwiftLanguageService/InlayHintManager.swift [hunk 20]
```diff
@@ -0,0 +1,316 @@
...
+}
+
+private extension InlayHint {
+  var labelAsString: String {
+    switch self.label {
+    case .string(let label):
+      return label
+
+    case .parts(let parts):
+      return parts.map { $0.value }.joined(separator: "")
```
Comment (ahoppen) [inline Sources/SwiftLanguageService/InlayHintManager.swift]: I think `separator` defaults to an empty string.

```suggestion
      return parts.map { $0.value }.joined()
```

File: Sources/SwiftLanguageService/SwiftLanguageService.swift (hunk 6 above)
Comment (ahoppen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: I have seen CI failures for race conditions that seem a lot less likely in the past, so I suspect that we would hit this race condition at some point. 

I think what we’d need to do in `getBackgroundComputedInlayHints` is something like the following:
- Run `textDocument/inlayHints`
- Check if the result matches the expectation
- If not, wait for a `inlayHints/refresh` request
- Check if the results now match the expectations

Comment (Steffeeen) [reply Sources/SwiftLanguageService/SwiftLanguageService.swift]: I renamed `getBackgroundComputedInlayHints` to `checkInlayHintsComputedInTheBackgroundMatch` and changed it to do what you suggested. I also verified that this fixes the potential timeout by adding a `Task.sleep()` call in one of the tests after the `sendChange()` call.

**Review by ahoppen — APPROVED** [review]
Looks good. Thank you 😄

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by Steffeeen** [comment]
Seems like `fulfillment()` does not have a default value for `timeout` on Linux and Windows. `fulfillment()` was implemented here: https://github.com/swiftlang/swift-corelibs-xctest/pull/453. But I'm not sure if the default value for the timeout was just missed in the corelibs PR or if the default value in the Xcode version was introduced later and the corelibs version was not adjusted.

Should I just set the timeout manually for all the calls in the tests or do we want to fix it upstream?

**Comment by ahoppen** [comment]
You should be able to use `fulfillmentOfOrThrow`, which handles the timeout already and also aborts the test if the expectation is not fulfilled.

**Comment by Steffeeen** [comment]
@swift-ci Please test

**Comment by Steffeeen** [comment]
@swift-ci Please test windows
