### PR TITLE
Ensure the string passed to `PathIsRelativeW` is null terminated

### LINKED ISSUE #2360: Windows CI unstable with SourceKitLSPTests
### Description

I've seen numerous CI jobs randomly failing with an issue in SourceKitLSPTests, which is unrelated to the changes being tested in the PR. Example logs:
```
21:58:22  Error: Error: swift exited with code 1.
21:58:22  Invocation:
21:58:22    swift test --scratch-path T:\x86_64-unknown-windows-msvc\SourceKitLSPTests --package-path C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\sourcekit-lsp -c release -debug-info-format none --parallel -Xcc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift-corelibs-libdispatch -Xcc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift-corelibs-libdispatch\src\BlocksRuntime -Xswiftc -IT:\5\lib\swift\host -Xswiftc -LT:\5\lib\swift\host -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\cmark\src\include -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\cmark\extensions\include -Xlinker -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\cmark\extensions\include -Xlinker T:\x86_64-unknown-windows-msvc\cmark-gfm-0.29.0.gfm.13\src\cmark-gfm.lib -Xlinker T:\x86_64-unknown-windows-msvc\cmark-gfm-0.29.0.gfm.13\extensions\cmark-gfm-extensions.lib -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift-system\Sources\CSystem\include -Xswiftc -IT:\x86_64-unknown-windows-msvc\System\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\System\lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\ToolsSupportCore\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\ToolsSupportCore\lib -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\llbuild\products\libllbuild\include -Xswiftc -IT:\x86_64-unknown-windows-msvc\LLBuild\products\llbuildSwift -Xlinker -LT:\x86_64-unknown-windows-msvc\LLBuild\lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\ArgumentParser\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\ArgumentParser\lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\Crypto\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\Crypto\lib -Xlinker T:\x86_64-unknown-windows-msvc\Crypto\lib\libCCryptoBoringSSL.lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\ASN1\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\ASN1\lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\PackageManager\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\PackageManager\lib -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift-markdown\Sources\CAtomic\inclde -Xlinker T:\x86_64-unknown-windows-msvc\Markdown\lib\CAtomic.lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\Markdown\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\Markdown\lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\Format\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\Format\lib -Xswiftc -IT:\x86_64-unknown-windows-msvc\IndexStoreDB\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB -Xlinker T:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB_CIndexStoreDB\CIndexStoreDB.lib -Xlinker T:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB_Core\Core.lib -Xlinker T:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB_Database\Database.lib -Xlinker T:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB_Index\Index.lib -Xlinker T:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB_LLVMSupport\LLVMSupport.lib -Xlinker T:\x86_64-unknown-windows-msvc\IndexStoreDB\Sources\IndexStoreDB_Support\Support.lib -Xlinker T:\x86_64-unknown-windows-msvc\LMDB\lib\CLMDB.lib -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\sourcekit-lsp\Sources\CAtomics\include -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\sourcekit-lsp\Sources\CSourcekitd\include -Xlinker T:\x86_64-unknown-windows-msvc\SourceKitLSP\lib\CSourcekitd.lib -Xswiftc -IC:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\sourcekit-lsp\Sources\CCompletionScoring\include -Xswiftc -IT:\x86_64-unknown-windows-msvc\SourceKitLSP\swift -Xlinker -LT:\x86_64-unknown-windows-msvc\SourceKitLSP\lib
21:58:22  Call stack:
21:58:22    at Invoke-Program, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1047
21:58:22    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 2015
21:58:22    at Invoke-IsolatingEnvVars, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1066
21:58:22    at Build-SPMProject, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1980
21:58:22    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 3900
21:58:22    at Invoke-IsolatingEnvVars, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1066
21:58:22    at Test-SourceKitLSP, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 3884
21:58:22    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 829
21:58:22    at Record-OperationTime, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 653
21:58:22    at Invoke-BuildStep, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 828
21:58:22    at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 4392
21:58:22  
21:58:22      at Invoke-Program, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1051
21:58:22      at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 2015
21:58:22      at Invoke-IsolatingEnvVars, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1066
21:58:22      at Build-SPMProject, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1980
21:58:22      at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 3900
21:58:22      at Invoke-IsolatingEnvVars, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 1066
21:58:22      at Test-SourceKitLSP, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 3884
21:58:22      at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 829
21:58:22      at Record-OperationTime, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 653
21:58:22      at Invoke-BuildStep, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 828
21:58:22      at <ScriptBlock>, C:\Users\swift-ci\jenkins\workspace\apple-llvm-project-pull-request-windows\swift\utils\build.ps1: line 4392
21:58:22    From System.Management.Automation.RuntimeException: Error: swift exited with code 1.
```

The job specifically is: https://ci-external.swift.org/job/apple-llvm-project-pull-request-windows/

It's causing people to re-run the job multiple times.

### Reproduction

```swift

```

### Expected behavior

Not to spuriously fail.

### Environment

Windows CI

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bnbarham**
`CompilationDatabaseTests` have been flakey on Windows since https://github.com/swiftlang/sourcekit-lsp/pull/2334. This didn't really introduce the failure though - it just added tests that now catch it.

The underlying cause is that `filename.isAbsolutePath` sometimes returns `true` for a relative path, which then causes the CWD to be prepended instead of the given `compileCommandsDirectory`.

`PathIsRelativeW` requires a null terminated string, so presumably we were hitting junk after the initial path that sometimes turned it into an absolute path. From the Windows docs:
> A pointer to a null-terminated string of maximum length MAX_PATH that
contains the path to search.

Fixes #2360
Resolves rdar://165006835

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

File: Sources/BuildServerIntegration/CompilationDatabase.swift [hunk 1]
```diff
@@ -206,7 +206,10 @@ enum CompilationDatabaseDecodingError: Error {
 fileprivate extension String {
   var isAbsolutePath: Bool {
     #if os(Windows)
-    Array(self.utf16).withUnsafeBufferPointer { buffer in
+    // PathIsRelativeW requires a null-terminated UTF16 encoded string
+    var path = Array(self.utf16)
+    path.append(0)
+    return path.withUnsafeBufferPointer { buffer in
```
Comment (ahoppen) [inline Sources/BuildServerIntegration/CompilationDatabase.swift]: You should be able to use `withCString(encodedAs:  UTF16.self)`, which should avoid one allocation (found this by seeing where else we call the Windows APIs and we’re doing that pattern for `PathCchIsRoot`.

```suggestion
    return path.withCString(encodedAs: UTF16.self) { buffer in
```

Comment (bnbarham) [reply Sources/BuildServerIntegration/CompilationDatabase.swift]: Ah nice, thanks!

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Windows

**Comment by bnbarham** [comment]
@swift-ci please test Windows

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Windows

**Comment by bnbarham** [comment]
@swift-ci please test Windows
