### PR TITLE
Fix issue that caused the `Reloading Package` progress indicator to be stuck

### LINKED ISSUE #1050: VSCode stuck on "Reloading Package"
This could be an issue with the Swift extension, but I'm seeing some log output from sourcekit-lsp that looks like it's kicking off this job:
```
[org.swift.sourcekit-lsp:notification-2] info 2024-02-13 10:38:33.104
Sending request to client (id: 1):
window/workDoneProgress/create
{
  "token" : "SourceKitLSP.SourceKitServer.reloadPackage"
}
---
[Trace - 10:38:33 AM] Received request 'window/workDoneProgress/create - (1)'.
Params: {
    "token": "SourceKitLSP.SourceKitServer.reloadPackage"
}
---
[org.swift.sourcekit-lsp:default] info 2024-02-13 10:38:33.107
Sending notification to client
$/progress
{
  "token" : "SourceKitLSP.SourceKitServer.reloadPackage",
  "value" : {
    "kind" : "begin",
    "title" : "Reloading Package"
  }
}
---
[Trace - 10:38:33 AM] Received notification '$/progress'.
Params: {
    "value": {
        "title": "Reloading Package",
        "kind": "begin"
    },
    "token": "SourceKitLSP.SourceKitServer.reloadPackage"
}
```
This is despite launching with a compilation database workspace (I would expect the `reloadPackage` job to only run in a SwiftPM workspace). Maybe a sub-project (not at the root) is being picked up as a SwiftPM workspace?
```
[org.swift.sourcekit-lsp:notification-22] info 2024-02-13 10:59:35.042
SwiftPM log: [info]: using 'Package.resolved' file as lock file
---
[org.swift.sourcekit-lsp:default] default 2024-02-13 10:59:35.797
SwiftPM log: [warning]: C:\workspace\<snip>\<snip>\.build\repositories\swift-argument-parser-54a11a8d is not valid git repository for 'https://github.com/apple/swift-argument-parser.git', will fetch again.
---
[org.swift.sourcekit-lsp:notification-22] debug 2024-02-13 10:59:36.221
SwiftPM log: [debug]: loading manifest for 'swift-sentry' v. unknown from memory cache
---
[org.swift.sourcekit-lsp:notification-22] debug 2024-02-13 10:59:36.227
SwiftPM log: [debug]: loading manifest for 'swift-identified-collections' v. 1.0.0 from memory cache
```
This doesn't seem to impact LSP functionality, but there's a constantly spinning "Reloading Package" notification in the bottom bar
image

### PR DESCRIPTION
**Pull request by ahoppen**
If any method in `reloadPacakge` threw, the `Reloading Package` progress indicator was stuck.

Also, change the message of the indicator to `SourceKit-LSP: Reloading Package` to make it easier to differentiate from status generated by the VS Code extension.

Fixes #1050
rdar://122899093

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

File: Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift [hunk 1]
```diff
@@ -205,6 +205,11 @@ extension SwiftPMWorkspace {
   /// dependencies.
   func reloadPackage() async throws {
     await reloadPackageStatusCallback(.start)
+    defer {
+      Task {
+        await reloadPackageStatusCallback(.end)
```
Comment (bnbarham) [inline Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:210]: Seems a bit weird for the end callback to be run at some point and not before `reloadPackages` returns. Could we sink what's in `reloadPackage` down into another function then call it here wrapped in `do` to make sure we always call end?

Comment (ahoppen) [reply Sources/SKSwiftPMWorkspace/SwiftPMWorkspace.swift:210]: Discussed offline and decided that it’s OK.
