### PR TITLE
Highlight references to actors like references to classes

### LINKED ISSUE #694: sourcekit-lsp does not recognize actor names as types
sourcekit-lsp is able to provide semantic highlights for `enum`, `struct`, `class`, `protocol`, and `typealias` type identifiers.

however, it is unable to highlight `actor` types as type identifiers. the following table summarizes the observed behavior under `swift-5.8-DEVELOPMENT-SNAPSHOT-2023-01-09-a`

```
$ swift --version
Swift version 5.8-dev (LLVM 08f7fecaf6cedb8, Swift a0b3f802c2ce715)
Target: x86_64-unknown-linux-gnu
```

| type | semantic token |
| ---- | -------------- |
| `enum` | `enum` |
| `struct` | `struct` |
| `class` | `class` |
| `actor` | **`identifier`** * |
| `protocol` | `interface` |
| `typealias` | `typeParameter` |

ideally we should have:

| type | semantic token |
| ---- | -------------- |
| `actor` | **`actor`** |

here is a screenshot:

image

the following test file may be helpful to investigate the issue:

```swift
enum EnumType
{
    case e
}
actor ActorType
{
    init()
    {
    }
}
final
class ClassType
{
    init()
    {
    }
}
struct StructType
{
    init()
    {
    }
}
protocol ProtocolType
{
}
typealias Typealias = ProtocolType

func test(_:any ProtocolType, _:any Typealias)
{
    let a:ActorType = .init()
    let c:ClassType = .init()
    let s:StructType = .init()
    let e:EnumType = .e
}
```

### PR DESCRIPTION
**Pull request by ahoppen**
We weren’t semantically highlighting references to actors because we missed the `ref_actor` case from the sourcekitd `annotations` response.

Fixes #694
rdar://104573568

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

File: Sources/SourceKitLSP/Swift/SyntaxHighlightingToken.swift [hunk 1]
```diff
@@ -91,6 +92,7 @@ public struct SyntaxHighlightingToken: Hashable {
       switch self {
       case .namespace: return "namespace"
       case .type: return "type"
+      case .actor: return "class" // Map
```
Comment (bnbarham) [inline Sources/SourceKitLSP/Swift/SyntaxHighlightingToken.swift:95]: Did you intend to write more for that comment?

**Review by bnbarham — APPROVED** [review]

File: Sources/SourceKitLSP/Swift/SyntaxHighlightingToken.swift (hunk 1 above)
Comment (ahoppen) [reply Sources/SourceKitLSP/Swift/SyntaxHighlightingToken.swift]: Oh, yes. I got distracted while writing it.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
