### PR TITLE
Infer build settings from sibling file if a file’s target cannot be determined

### LINKED ISSUE #2319: New files opened in helix editor lack symbols from the same package
### Swift version

swift-driver version: 1.127.14.1 Apple Swift version 6.2 (swiftlang-6.2.0.19.9 clang-1700.3.19.1) Target: arm64-apple-macosx26.0

### Platform

macOS 26

### Editor

Helix

### Description

When I create a new file in helix (e.g.,  by using `:o <filepath>`), although code completion and diagnostics keep working on this file, they lack any of the symbols of the module the file is placed in. Only after restarting the server via `:LspRestart` do the symbols appear correctly. 

From what I could gather in the logs, source-kit receives the `textDocument/didOpen` notification from helix, but it does not seem to recognize the workspace of the file:

```
Build settings for file:///Users/dfortes/Developer/dump/SomeProject/Sources/SomeProject/Other.swift (1/1)
Compiler Arguments:
-sdk
/Applications/Xcode-26.0.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk
/Users/dfortes/Developer/dump/SomeProject/Sources/SomeProject/Other.swift

Working directory:
<nil>
```
and
```
Producing syntactic diagnostics from the built-in swift-syntax because we have fallback build settings)
```

### Steps to Reproduce

Create a new project:
```
mkdir SomeProject
cd SomeProject
swift package init
```

Open the helix editor:
```
hx Sources/SomeProject/SomeProject.swift
```
Set the source code to something like:
```
struct Model {
	var x: Int
}
```

Open a new file by using the command: `:o Sources/SomeProject/OtherFile.swift`; code completion will still work for libraries like Foundation, but the `Model` struct won't be found.  

### Logging

[sourcekit-lsp-diagnose-2025-10-06T15-23-13-03-00.zip](https://github.com/user-attachments/files/22728359/sourcekit-lsp-diagnose-2025-10-06T15-23-13-03-00.zip)

### PR DESCRIPTION
**Pull request by ahoppen**
When we can’t determine the target of a source file (eg. because the file hasn’t been saved to disk yet or because the package hasn’t been reloaded yet to take the new file into account), try and find a file with the same language in the same directory and use that file to infer fallback settings for the current file that are more sophisticated than just the SDK.

Fixes #2319

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

File: Sources/BuildServerIntegration/BuildServerManager.swift [hunk 1]
```diff
@@ -1135,27 +1179,57 @@ package actor BuildServerManager: QueueBasedMessageHandler {
...
+    }
+
     func mainFileAndSettings(
       basedOn document: DocumentURI
     ) async -> (mainFile: DocumentURI, settings: FileBuildSettings)? {
       let mainFile = await self.mainFile(for: document, language: language)
-      let settings: FileBuildSettings? = await orLog("Getting build settings") {
-        let target =
+      let settings: FileBuildSettings? = await orLog("Getting build settings") { () -> FileBuildSettings? in
+        // enum TargetResult {
```
Comment (bnbarham) [inline Sources/BuildServerIntegration/BuildServerManager.swift]: Leftover before creating `WithTimeoutResult` I assume?

Comment (ahoppen) [reply Sources/BuildServerIntegration/BuildServerManager.swift]: Yes, exactly.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
