### PR TITLE
Reload a file when other files within the same module or a `.swiftmodule` file has been changed

### LINKED ISSUE #620: Jump to definition requires a reload after build
If I load a project with dependencies into VS Code which has not been built when I right click on a symbol to go to definition (run a textDocument/definition request) it returns an empty result. This is a known issue.

If I then build the project and repeat I still get an empty result. I would assume once the project is built SourceKit-LSP should be able to return a position for the symbol.

I have to restart VS Code (ie restart the SourceKit-LSP server) for SourceKit-LSP to return a valid position for the symbol.

### LINKED ISSUE #1116: Diagnostics are not refreshed after build when a new file is added
Steps to reproduce:
1. Add a new file with some class.
2. Reference this class within the same target.
3. Build the project using `xcodebuild` command.

Actual result:
The build succeeds, LSP doesn't print any errors in the log, LSP still shows issues:
image

Expected result:
LSP should be automatically refreshed and errors should disappear.

Workaround:
Restart LSP (in Neovim `:LspRestart`).

Version:
Sourcekit-lsp provided by Xcode Version 15.2 (15C500b)

Related issue:
https://github.com/wojciech-kulik/xcodebuild.nvim/issues/56

Notes:
I reproduced it both in Neovim and Visual Studio Code, so I guess it's not the LSP client's fault.

### PR DESCRIPTION
**Pull request by ahoppen**
When the client sends us `workspace/didChangeWatchedFiles` notification of an updated `.swift` file, we should refresh the other open files in that module since they might be referencing functions from that updated file.

If a `.swiftmodule` file has been updated, we refresh all the files within the package since they might import that module. Technically, we would only need to refresh files that are in module that are downstream of the updated module but we don’t currently have that information easily available from SwiftPM. Also, usually, if the client has a file from a low-level module open, he’ll be working on that module which means that such an optimization won’t help. The real solution here is to wait for us to finish preparation (which we would exactly know when it finishes since sourcekit-lsp would schedule it) but for that we need to implement background preparation.

Fixes #620
Fixes #1116
rdar://99329579
rdar://123971779

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test macOS

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

File: Sources/SourceKitLSP/Swift/SwiftLanguageService.swift [hunk 1]
```diff
@@ -189,6 +198,17 @@ public actor SwiftLanguageService: LanguageService {
     self.generatedInterfacesPath = options.generatedInterfacesPath.asURL
     try FileManager.default.createDirectory(at: generatedInterfacesPath, withIntermediateDirectories: true)
     self.diagnosticReportManager = nil  // Needed to work around rdar://116221716
+
+    // The debounce duration of 500ms was chosen arbitrarily without scientific research.
```
Comment (bnbarham) [inline Sources/SourceKitLSP/Swift/SwiftLanguageService.swift:202]:
```suggestion
    // The debounce duration of 500ms was chosen arbitrarily without any real benchmarking.
```

File: Sources/SourceKitLSP/Swift/SwiftLanguageService.swift [hunk 2]
```diff
@@ -339,13 +363,15 @@ extension SwiftLanguageService {
   }
 
   public func documentDependenciesUpdated(_ uri: DocumentURI) async {
-    guard let snapshot = try? self.documentManager.latestSnapshot(uri) else {
-      return
+    // FIXME: Debounce, otherwise it will get called over and over
```
Comment (bnbarham) [inline Sources/SourceKitLSP/Swift/SwiftLanguageService.swift:366]: Any reason not to debounce it now?

File: Sources/SKSwiftPMWorkspace/SwiftPMBuildSystem.swift [hunk 3]
```diff
@@ -368,6 +391,35 @@ extension SwiftPMBuildSystem: SKCore.BuildSystem {
...
+        continue
+      }
+      filesWithUpdatedDependencies.formUnion(target.sources.map { DocumentURI($0) })
+    }
+
+    // If a `.swiftmodule` file is updated, this means that we have performed a build / are
+    // performing a build and files that depend on this module have updated dependencies.
+    // We don't have access to the build graph from the SwiftPM API offered to SourceKit-LSP to figure out which files
+    // depend on the updated module, so assume that all files have updated dependencies. Currently, this does not matter
+    // because `SwiftLanguageService` sends a `dependencyUpdated` request to sourcekitd, which is global anyway.
```
Comment (bnbarham) [inline Sources/SKSwiftPMWorkspace/SwiftPMBuildSystem.swift:413]: FWIW that only seems to impact completion, not eg. cursor info.

**Review by bnbarham — APPROVED** [review]

File: Sources/SourceKitLSP/Swift/SwiftLanguageService.swift (hunk 2 above)
Comment (ahoppen) [reply Sources/SourceKitLSP/Swift/SwiftLanguageService.swift:366]: Oh, this was just an in-development comment that I forgot to remove. We `fileDependenciesUpdated` on the `BuildSystem` level now, so this isn’t needed. I just put it here at some point to remind myself that we need to debounce somewhere.

File: Sources/SKSwiftPMWorkspace/SwiftPMBuildSystem.swift (hunk 3 above)
Comment (ahoppen) [reply Sources/SKSwiftPMWorkspace/SwiftPMBuildSystem.swift:413]: Ah, we do also reopen the file. I updated the comment to just remove the

> Currently, this does not matter because `SwiftLanguageService` sends a `dependencyUpdated` request to sourcekitd, which is global anyway.

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
