### PR TITLE
Standardize file paths when attempting to find toolchains

### LINKED ISSUE #2174: Language support not available on Windows
**Describe the bug**
Basically, no completion, intellisense, errors, etc. Nothing kinda works.

**To Reproduce**
Be on windows
Install swift with winget (6.1.0)
Install vscode
Install swift extension for vscode
Create a project (either with swift vscode commands or the CLI)
Open a .swift file
done, nothing works

**Expected behavior**
Having basic code completion, type inference and error reporting

**Environment**
 - OS: Windows 11 23H2
 - Swift version: Swift version 6.1 (swift-6.1-RELEASE) \
                          Target: x86_64-unknown-windows-msvc
 - Visual Studio Code version: 1.100.3
 - vscode-swift version: 2.3.20250521

**Additional context**
Image
Image
Image

and code is working with cli:
Image

till now, I was only able to "reliably" use swift with a proper lsp support was in an wsl ubuntu, and it was getting heavier and heavier (too much) with each line of code
maybe this all is related to the constant CPU hogging problem Image, but either way

### PR DESCRIPTION
**Pull request by bnbarham**
`containingXCToolchain` loops infinitely when given eg. `C:\foo\..\bar`. The underlying cause is that `deletingLastPathComponent` does not remove the `..` on Windows. On macOS it's potentially worse - it *adds* `..`. We don't see the infinite loop on macOS/Linux though because `AbsolutePath` already removes them (which is not the case on Windows).

Resolves #2174.

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

File: Sources/ToolchainRegistry/Toolchain.swift [hunk 1]
```diff
@@ -369,7 +369,7 @@ public final class Toolchain: Sendable {
 func containingXCToolchain(
   _ path: URL
 ) -> (XCToolchainPlist, URL)? {
-  var path = path
+  var path = path.standardizedFileURL
```
Comment (ahoppen) [inline Sources/ToolchainRegistry/Toolchain.swift]: I would suggest using `.realpath` instead of `standardizedFileURL` to avoid the `/tmp` vs `/private/tmp` issue on macOS.

**Comment by bnbarham** [comment]
> Also, we should check how this behaves if we discover two toolchains that have different paths (due to symlinks) but point to the same realpath. This is usually the case on macOS when you have open source toolchains installed and swift-latest.xctoolchain is a symlink to the latest installed toolchain. Ideally, we would only keep one copy of these toolchains in ToolchainRegistry now because they are identical.

FWIW this already happens today - they both have the same identifier, so we only use one and the other is skipped (with an error logged).

> I think this will cause issues if you have a toolchain with a symlink during the discovery phase and the BSP server returns a path that contains the symlink

Good point, I'll fix up the lookups.

> I would suggest using .realpath instead of standardizedFileURL to avoid the /tmp vs /private/tmp issue on macOS.

Yeah, this is the cause of the test failures at the moment (well, sort of, in that the test doesn't do a standardize and thus we get different /tmp vs /private/tmp).

**Comment by bnbarham** [comment]
@swift-ci please test

File: Sources/ToolchainRegistry/Toolchain.swift [hunk 2]
```diff
@@ -366,10 +366,20 @@ public final class Toolchain: Sendable {
...
 /// Find a containing xctoolchain with plist, if available.
-func containingXCToolchain(
+private func containingXCToolchain(
   _ path: URL
 ) -> (XCToolchainPlist, URL)? {
-  var path = path
+  // `deletingLastPathComponent` only makes sense on resolved paths (ie. those without symlinks or `..`). Any given
+  // toolchain path should have already been realpathed, but since this can turn into an infinite loop otherwise, it's
+  // better to be safe than sorry.
+  guard let resolvedPath = try? path.realpath else {
```
Comment (ahoppen) [inline Sources/ToolchainRegistry/Toolchain.swift]: Use `orLog` here so that we get some indication in case `realpath` fails, in which case we would only return `nil` here without logging the fault below?

File: Sources/ToolchainRegistry/ToolchainRegistry.swift [hunk 3]
```diff
@@ -219,7 +220,9 @@ package final actor ToolchainRegistry {
     }
 
     let toolchainsAndReasons = toolchainPaths.compactMap {
-      if let toolchain = Toolchain($0.path) {
+      if let resolvedPath = try? $0.path.realpath,
```
Comment (ahoppen) [inline Sources/ToolchainRegistry/ToolchainRegistry.swift]: Same here, should we use `orLog`. I imagine this could help if the user has broken symlinks in their path. Or generally for all uses of `realpath`.

File: Sources/ToolchainRegistry/ToolchainRegistry.swift [hunk 4]
```diff
@@ -283,7 +286,18 @@ package final actor ToolchainRegistry {
   /// If we have a toolchain in the toolchain registry that contains the compiler with the given URL, return it.
   /// Otherwise, return `nil`.
   package func toolchain(withCompiler compiler: URL) -> Toolchain? {
-    return toolchainsByCompiler[compiler]
+    if let resolvedPath = try? compiler.realpath {
+      return toolchainsByCompiler[resolvedPath]
```
Comment (ahoppen) [inline Sources/ToolchainRegistry/ToolchainRegistry.swift]: We should run `realpath` when populating `toolchainsByCompiler` as well to cover symlinks within the toolchain, eg. `swift` and `swiftc` to `swift-driver`.

File: Sources/ToolchainRegistry/ToolchainRegistry.swift [hunk 5]
```diff
@@ -283,7 +286,18 @@ package final actor ToolchainRegistry {
   /// If we have a toolchain in the toolchain registry that contains the compiler with the given URL, return it.
   /// Otherwise, return `nil`.
   package func toolchain(withCompiler compiler: URL) -> Toolchain? {
-    return toolchainsByCompiler[compiler]
+    if let resolvedPath = try? compiler.realpath {
```
Comment (ahoppen) [inline Sources/ToolchainRegistry/ToolchainRegistry.swift]: This means that we need to run `realpath` and thus hit the filesystem for every entry in a JSON compilation database. Should we try and look up the non-realpath version first? And if we have a hit using the `realpath`, we can add a mapping for the original path to the toolchain as well as a cache. That way we only need to realpath every given path in a JSON compilation database once.

File: Sources/ToolchainRegistry/ToolchainRegistry.swift [hunk 6]
```diff
@@ -283,7 +286,18 @@ package final actor ToolchainRegistry {
...
+    }
+    return nil
+  }
+
+  /// If we have a toolchain in the toolchain registry with the given URL, return it. Otherwise, return `nil`.
+  package func toolchain(withPath path: URL) -> Toolchain? {
+    if let resolvedPath = try? path.realpath {
+      return toolchainsByPath[resolvedPath]
+    }
+    return nil
```
Comment (ahoppen) [inline Sources/ToolchainRegistry/ToolchainRegistry.swift]: Similar to my comment on `toolchain(withCompiler:)`, should we try a non-realpath lookup first and then cache if necessary to avoid hitting the file system unnecessarily? E.g. something like

```swift
if let toolchain = toolchainsByPath[path] {
  return toolchain
}
guard let realpath = orLog("Realpath toolchain", { try path.realpath }) else {
  return nil
}
guard let toolchain = lchainsByPath[realpath] else {
  return nil
}
// Cache mapping of non-realpath to the realpath toolchain for faster subsequent lookups
toolchainsByPath[path] = toolchain
return toolchain
```

File: Sources/ToolchainRegistry/Toolchain.swift (hunk 2 above)
Comment (bnbarham) [reply Sources/ToolchainRegistry/Toolchain.swift]: Sure, I didn't want to be too spammy here but... 🤷

File: Sources/ToolchainRegistry/ToolchainRegistry.swift (hunk 4 above)
Comment (bnbarham) [reply Sources/ToolchainRegistry/ToolchainRegistry.swift]: Ah, good point. I didn't do this since we already realpathed the toolchain path coming into ToolchainRegistry, but forgot about the case the binaries themselves could be. We could just realpath the parent folder here?

EDIT: Hmmm, but we don't know the "toolchain" path in order to do that. I don't love the idea of realpathing to swift-driver though.

Comment (bnbarham) [reply Sources/ToolchainRegistry/ToolchainRegistry.swift]: So I ended up going with just realpathing the parent dir, which while not "correct" ("bin" might itself be a symlink), it seems sufficiently unlikely to me for it not to matter. Happy to change if you disagree, though ideally we'd have a third solution as I'd really like to avoid realpathing the binaries themselves.

File: Sources/ToolchainRegistry/ToolchainRegistry.swift (hunk 5 above)
Comment (bnbarham) [reply Sources/ToolchainRegistry/ToolchainRegistry.swift]: Little sad to make all these mutable, but we'll likely need to do that even more in the future anyway (to allow registering toolchains as they're added) 👍

**Comment by bnbarham** [comment]
@swift-ci please test

File: Sources/ToolchainRegistry/Toolchain.swift (hunk 2 above)
Comment (ahoppen) [reply Sources/ToolchainRegistry/Toolchain.swift]: I wouldn’t expect this to fails, so if it does, I want to know.

File: Sources/ToolchainRegistry/ToolchainRegistry.swift (hunk 4 above)
Comment (ahoppen) [reply Sources/ToolchainRegistry/ToolchainRegistry.swift]: I think it’s fair enough to assume that `bin` is not a symlink. If somebody starts symlinking `bin`, I really want to know what they are trying to achieve.

**Review by ahoppen — APPROVED** [review]
Looks good. Thank you!

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by ahoppen** [comment]
@swift-ci Please test Windows
