### PR TITLE
Adjust test cases for fixed enum case rename

### LINKED ISSUE #1228: Support renaming argument labels of enum cases
We currently don’t support renaming argument labels of enum cases. We should. The tricky part is that enum cases can add and remove the label and colon, similar to function calls. This means that we need support for this in sourcekitd. Maybe we can treat enum case declarations the same way we treat function calls.

The following tests should pass

```swift
func testRenameEnumCaseWithUnlabeledAssociatedValue() async throws {
  try await assertSingleFileRename(
    """
    enum MyEnum {
      case 1️⃣myCase(String)
    }
    """,
    newName: "newName(_:)",
    expectedPrepareRenamePlaceholder: "myCase(_:)",
    expected: """
      enum MyEnum {
        case newName(String)
      }
      """
  )
}

func testAddLabelToEnumCase() async throws {
  try await assertSingleFileRename(
    """
    enum MyEnum {
      case 1️⃣myCase(String)
    }
    """,
    newName: "newName(newLabel:)",
    expectedPrepareRenamePlaceholder: "myCase(_:)",
    expected: """
      enum MyEnum {
        case newName(newLabel: String)
      }
      """
  )
}

func testRemoveLabelToEnumCase() async throws {
  try await assertSingleFileRename(
    """
    enum MyEnum {
      case 1️⃣myCase(label: String)
    }
    """,
    newName: "newName(_:)",
    expectedPrepareRenamePlaceholder: "myCase(label:)",
    expected: """
      enum MyEnum {
        case newName(String)
      }
      """
  )
}
```

### PR DESCRIPTION
**Pull request by ahoppen**
Linked to https://github.com/apple/swift-syntax/pull/2678 and https://github.com/apple/swift/pull/74241

---

Enum case rename is fixed by changes in sourcekitd. We can remove our workaround for the issue and add test cases that test the rename behavior.

Fixes #1228
rdar://127646036

### CODE REVIEW

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2678
https://github.com/apple/swift/pull/74241

@swift-ci Please test

File: Tests/SourceKitLSPTests/RenameTests.swift [hunk 1]
```diff
@@ -1187,39 +1188,127 @@ final class RenameTests: XCTestCase {
...
+        }
+        """
+    )
+  }
+
+  func testRenameEnumCaseWithUnderscoreToLabelNotMatchingInternalName() async throws {
+    try await SkipUnless.sourcekitdCanRenameEnumCaseLabels()
+    // Note that the renamed code doesn't compile because enum cases can't have an external and internal parameter name.
+    // But it's probably the best thing we can do because we don't want to erase the user-specified internal name, which
+    // they didn't request to rename. Also, this is a pretty niece case and having a special case for it is probably not
```
Comment (hamishknight) [inline Tests/SourceKitLSPTests/RenameTests.swift:1290]:
```suggestion
    // they didn't request to rename. Also, this is a pretty niche case and having a special case for it is probably not
```

**Review by hamishknight — APPROVED** [review]

File: Tests/SourceKitLSPTests/RenameTests.swift [hunk 2]
```diff
@@ -1187,39 +1188,127 @@ final class RenameTests: XCTestCase {
...
+      func test() {
+        _ = MyEnum.2️⃣myCase(label: "abc")
       }
       """,
       newName: "newName(_:)",
-      expectedPrepareRenamePlaceholder: "myCase",
+      expectedPrepareRenamePlaceholder: "myCase(label:)",
+      expected: """
+        enum MyEnum {
+          case newName(_ label: String)
```
Comment (hamishknight) [inline Tests/SourceKitLSPTests/RenameTests.swift:1224]: Should we be dropping the label completely here?

Comment (ahoppen) [reply Tests/SourceKitLSPTests/RenameTests.swift:1224]: I think it’s valuable to keep it as an internal label, similar to what we do for function completion (and yes, also easier to implement 🙈)

**Comment by ahoppen** [comment]
https://github.com/apple/swift/pull/74241
https://github.com/apple/sourcekit-lsp/pull/1471

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2678
https://github.com/apple/swift/pull/74241

@swift-ci Please test

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2678
https://github.com/apple/swift/pull/74241

@swift-ci Please test Windows

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2678
https://github.com/apple/swift/pull/74241

@swift-ci Please test macOS

**Comment by ahoppen** [comment]
https://github.com/apple/swift-syntax/pull/2678
https://github.com/apple/swift/pull/74241

@swift-ci Please test Linux
