### PR TITLE
Pass toolsets through to preparation for the SwiftPM build server

### LINKED ISSUE #2373: [Embedded] Can't find any module when background indexing is turned on
### Swift version

swift-DEVELOPMENT-SNAPSHOT-2025-11-25-a, swift-DEVELOPMENT-SNAPSHOT-2025-11-26-a

### Platform

macOS 26.1

### Editor

Visual Studio Code 1.106.2 with Swift extension, Vim 9.1 with vim-lsp

### Description

Sourcekit-LSP has enabled `backgroundIndexing` by default on the main branch lately. However, since then, code completion has been broken.

### Steps to Reproduce

Steps:

1. Clone https://github.com/kkebo/embedded-lsp-mre
2. Run `cd embedded-lsp-mre`
3. Run `swiftly install`
4. Open the current directory with VS Code or Vim
5. Open `Sources/Foo/Foo.swift`

Expected behavior:

No errors are displayed on a editor.

Actual behavior:

The "No such module 'Bar'" error is displayed at `import Bar`.

However, it can be built with `swift build -c release --triple aarch64-none-none-elf --toolset toolset.json` successfully.

In addition, if you add `"backgroundIndexing": false` to `.sourcekit-lsp/config.json`, the error disappears and it works fine just like it did before.

### Logging

[sourcekit-lsp-diagnose-2025-11-28T21-17-23+09-00.zip](https://github.com/user-attachments/files/23823311/sourcekit-lsp-diagnose-2025-11-28T21-17-23%2B09-00.zip)

### PR DESCRIPTION
**Pull request by bnbarham**
Also adds some logging to the synchronize request so that it's obvious when background indexing is being skipped.

Fixes #2373
Resolves rdar://165519940

### CODE REVIEW

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test

File: Tests/BuildServerIntegrationTests/SwiftPMBuildServerTests.swift [hunk 1]
```diff
@@ -1111,6 +1111,61 @@ struct SwiftPMBuildServerTests {
...
+          }
+        }
+        """,
+      ],
+      manifest: """
+        let package = Package(
+          name: "MyLibrary",
+          targets: [
+           .target(name: "Foo", dependencies: ["Bar"]),
+           .target(name: "Bar"),
```
Comment (ahoppen) [inline Tests/BuildServerIntegrationTests/SwiftPMBuildServerTests.swift]:
```suggestion
            .target(name: "Foo", dependencies: ["Bar"]),
            .target(name: "Bar"),
```

**Comment by ahoppen** [comment]
@swift-ci Please test Windows

File: Tests/BuildServerIntegrationTests/SwiftPMBuildServerTests.swift (hunk 1 above)
Comment (bnbarham) [reply Tests/BuildServerIntegrationTests/SwiftPMBuildServerTests.swift]: Nice eye 😅 This was a copy paste and de-indent, so I suspect we have this somewhere else (don't remember where I got it from) or de-indent did a weird number of spaces 🤷‍♂️

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform

**Comment by bnbarham** [comment]
@swift-ci please test

**Comment by bnbarham** [comment]
Updated the test to include checking options and skipping on Windows due to https://github.com/swiftlang/swift-package-manager/issues/9438.

**Comment by bnbarham** [comment]
@swift-ci please test Windows platform
